#================================================================================
# Auto Generated Code for SeluUdoPackage
#================================================================================

# define relevant directories
SRC_DIR := ./

# define library name and corresponding directory
export LIB_DIR := ../../../libs/$(TARGET)

library := $(LIB_DIR)/libUdoSeluUdoPackageImplCpu.so


# define target architecture if not previously defined, default is x86
ifndef TARGET_AARCH_VARS
TARGET_AARCH_VARS:= -march=x86-64
endif

# specify package paths, should be able to override via command line?
UDO_PACKAGE_ROOT =/home/pratiksha/Downloads/snpe-1.51.0.2663/UDO/Selu/SeluUdoPackage

include ../../../common.mk

